version: '3.8'  # Ensure using a compatible version for GPU support
services:
  serge:
    restart: on-failure
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./web:/usr/src/app/web/
      - ./api:/usr/src/app/api/
      - datadb:/data/db
      - weights:/usr/src/app/weights/
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8008:8008"
      - "9124:9124"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

volumes:
  datadb:
  weights:
